-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS plpgsql;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS bands;
CREATE SCHEMA IF NOT EXISTS bookings;
CREATE SCHEMA IF NOT EXISTS chat;
CREATE SCHEMA IF NOT EXISTS events;
CREATE SCHEMA IF NOT EXISTS geo;
CREATE SCHEMA IF NOT EXISTS media;
CREATE SCHEMA IF NOT EXISTS music;
CREATE SCHEMA IF NOT EXISTS notifications;
CREATE SCHEMA IF NOT EXISTS payments;
CREATE SCHEMA IF NOT EXISTS public;
CREATE SCHEMA IF NOT EXISTS reviews;
CREATE SCHEMA IF NOT EXISTS social; 
CREATE SCHEMA IF NOT EXISTS studios;

CREATE TABLE IF NOT EXISTS auth.email_verification_tokens
(
    token_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    token_hash text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    consumed_at timestamp with time zone,
    ip inet,
    user_agent text COLLATE pg_catalog."default",
    CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (token_id),
    CONSTRAINT uq_email_verification_token_hash UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS auth.oauth_accounts
(
    oauth_account_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    provider text COLLATE pg_catalog."default" NOT NULL,
    provider_user_id uuid NOT NULL,
    access_token text COLLATE pg_catalog."default",
    refresh_token text COLLATE pg_catalog."default",
    token_expires_at timestamp with time zone,
    scopes text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT oauth_accounts_pkey PRIMARY KEY (oauth_account_id),
    CONSTRAINT oauth_accounts_user_id_provider_key UNIQUE (user_id, provider),
    CONSTRAINT uq_oauth_accounts_provider_provider_user_id UNIQUE (provider, provider_user_id),
    CONSTRAINT uq_oauth_accounts_user_id_provider UNIQUE (user_id, provider)
);

CREATE TABLE IF NOT EXISTS auth.password_reset_tokens
(
    token_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    token_hash text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    consumed_at timestamp with time zone,
    ip inet,
    user_agent text COLLATE pg_catalog."default",
    CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (token_id),
    CONSTRAINT uq_password_reset_token_hash UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS auth.sessions
(
    session_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    refresh_token_hash text COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    ip inet,
    expires_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    revoked_at timestamp with time zone,
    CONSTRAINT sessions_pkey PRIMARY KEY (session_id),
    CONSTRAINT uq_sessions_refresh_token_hash UNIQUE (refresh_token_hash)
);

CREATE TABLE IF NOT EXISTS auth.user_roles
(
    user_role_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    role text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_role_id),
    CONSTRAINT uq_user_roles_user_id_role UNIQUE (user_id, role),
    CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role)
);

CREATE TABLE IF NOT EXISTS auth.users
(
    user_id uuid NOT NULL DEFAULT gen_random_uuid(),
    email citext COLLATE pg_catalog."default" NOT NULL,
    username citext COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    display_name text COLLATE pg_catalog."default",
    bio text COLLATE pg_catalog."default",
    phone text COLLATE pg_catalog."default",
    birthdate date,
    place_id uuid,
    profile_visibility text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    email_verified boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS bands.band_genres
(
    band_genre_id uuid NOT NULL DEFAULT gen_random_uuid(),
    band_id uuid NOT NULL,
    genre_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT band_genres_pkey PRIMARY KEY (band_genre_id),
    CONSTRAINT uq_band_genres_band_id_genre_id UNIQUE (band_id, genre_id)
);

CREATE TABLE IF NOT EXISTS bands.band_invite
(
    invite_id uuid NOT NULL DEFAULT gen_random_uuid(),
    band_id uuid NOT NULL,
    from_user_id uuid NOT NULL,
    to_user_id uuid NOT NULL,
    message text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    responded_at timestamp with time zone,
    CONSTRAINT band_invite_pkey PRIMARY KEY (invite_id)
);

CREATE TABLE IF NOT EXISTS bands.band_members
(
    band_member_id uuid NOT NULL DEFAULT gen_random_uuid(),
    band_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    joined_at timestamp with time zone,
    left_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    description text COLLATE pg_catalog."default",
    CONSTRAINT band_members_pkey PRIMARY KEY (band_member_id),
    CONSTRAINT uq_band_members_band_id_user_id UNIQUE (band_id, user_id)
);

CREATE TABLE IF NOT EXISTS bands.band_openings
(
    opening_id uuid NOT NULL DEFAULT gen_random_uuid(),
    band_id uuid NOT NULL,
    instrument_id uuid NOT NULL,
    description text COLLATE pg_catalog."default",
    place_id uuid,
    status text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT band_openings_pkey PRIMARY KEY (opening_id)
);

CREATE TABLE IF NOT EXISTS bands.bands
(
    band_id uuid NOT NULL DEFAULT gen_random_uuid(),
    owner_user_id uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    place_id uuid,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT bands_pkey PRIMARY KEY (band_id)
);

CREATE TABLE IF NOT EXISTS bands.opening_applications
(
    application_id uuid NOT NULL DEFAULT gen_random_uuid(),
    opening_id uuid NOT NULL,
    user_id uuid NOT NULL,
    message text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT opening_applications_pkey PRIMARY KEY (application_id),
    CONSTRAINT uq_opening_applications_opening_id_user_id UNIQUE (opening_id, user_id)
);

CREATE TABLE IF NOT EXISTS bookings.booking_status_history
(
    history_id uuid NOT NULL DEFAULT gen_random_uuid(),
    booking_id uuid NOT NULL,
    status text COLLATE pg_catalog."default",
    changed_at timestamp with time zone,
    changed_by uuid,
    note text COLLATE pg_catalog."default",
    CONSTRAINT booking_status_history_pkey PRIMARY KEY (history_id)
);

CREATE TABLE IF NOT EXISTS bookings.bookings
(
    booking_id uuid NOT NULL DEFAULT gen_random_uuid(),
    room_id uuid NOT NULL,
    user_id uuid NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    ends_at timestamp with time zone NOT NULL,
    status text COLLATE pg_catalog."default",
    total_amount numeric(12, 2),
    notes text COLLATE pg_catalog."default",
    cancelled_at timestamp with time zone,
    cancellation_reasons text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT bookings_pkey PRIMARY KEY (booking_id)
);

CREATE TABLE IF NOT EXISTS bookings.receipts
(
    receipt_id uuid NOT NULL DEFAULT gen_random_uuid(),
    booking_id uuid NOT NULL,
    pdf_url text COLLATE pg_catalog."default",
    emailed_to_user_at timestamp with time zone,
    emailed_to_owner_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT receipts_pkey PRIMARY KEY (receipt_id),
    CONSTRAINT uq_receipts_booking_id UNIQUE (booking_id)
);

CREATE TABLE IF NOT EXISTS chat.conversation_members
(
    conversation_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role text COLLATE pg_catalog."default",
    joined_at timestamp with time zone,
    left_at timestamp with time zone,
    CONSTRAINT uq_conversation_members_conversation_id_user_id PRIMARY KEY (conversation_id, user_id)
);

CREATE TABLE IF NOT EXISTS chat.conversations
(
    conversation_id uuid NOT NULL DEFAULT gen_random_uuid(),
    conversation_type text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT conversations_pkey PRIMARY KEY (conversation_id)
);

CREATE TABLE IF NOT EXISTS chat.message_reads
(
    message_read_id uuid NOT NULL DEFAULT gen_random_uuid(),
    message_id uuid NOT NULL,
    user_id uuid NOT NULL,
    read_at timestamp with time zone,
    CONSTRAINT message_reads_pkey PRIMARY KEY (message_read_id),
    CONSTRAINT uq_message_reads_message_id_user_id UNIQUE (message_id, user_id)
);

CREATE TABLE IF NOT EXISTS chat.messages
(
    message_id uuid NOT NULL DEFAULT gen_random_uuid(),
    conversation_id uuid NOT NULL,
    sender_user_id uuid NOT NULL,
    body text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    edited_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT messages_pkey PRIMARY KEY (message_id)
);

CREATE TABLE IF NOT EXISTS events.event_attendees
(
    event_attendee_id uuid NOT NULL DEFAULT gen_random_uuid(),
    event_id uuid NOT NULL,
    user_id uuid NOT NULL,
    status text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT event_attendees_pkey PRIMARY KEY (event_attendee_id),
    CONSTRAINT uq_event_attendees_event_id_user_id UNIQUE (event_id, user_id)
);

CREATE TABLE IF NOT EXISTS events.event_band_attendance
(
    event_id uuid NOT NULL,
    band_id uuid NOT NULL,
    status text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT event_band_attendance_pkey PRIMARY KEY (event_id, band_id)
);

CREATE TABLE IF NOT EXISTS events.event_invites
(
    invite_id uuid NOT NULL DEFAULT gen_random_uuid(),
    event_id uuid NOT NULL,
    from_user_id uuid NOT NULL,
    to_user_id uuid NOT NULL,
    status text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    responded_at timestamp with time zone,
    CONSTRAINT event_invites_pkey PRIMARY KEY (invite_id),
    CONSTRAINT uq_event_invites_event_id_to_user_id UNIQUE (event_id, to_user_id)
);

CREATE TABLE IF NOT EXISTS events.events
(
    event_id uuid NOT NULL DEFAULT gen_random_uuid(),
    host_user_id uuid NOT NULL,
    host_band_id uuid,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    starts_at timestamp with time zone,
    ends_at timestamp with time zone,
    timezone text COLLATE pg_catalog."default",
    capacity integer,
    visibility text COLLATE pg_catalog."default",
    place_id uuid,
    is_cancelled boolean DEFAULT false,
    cancel_reason text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT events_pkey PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS geo.places
(
    place_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."default" NOT NULL,
    address_line1 text COLLATE pg_catalog."default",
    address_line2 text COLLATE pg_catalog."default",
    city text COLLATE pg_catalog."default",
    region text COLLATE pg_catalog."default",
    postal_code text COLLATE pg_catalog."default",
    country text COLLATE pg_catalog."default",
    lat double precision,
    lng double precision,
    geom geometry(Point,4326),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    provider text COLLATE pg_catalog."default",
    external_id text COLLATE pg_catalog."default",
    CONSTRAINT places_pkey PRIMARY KEY (place_id)
);

CREATE TABLE IF NOT EXISTS media.media
(
    media_id uuid NOT NULL DEFAULT gen_random_uuid(),
    url text COLLATE pg_catalog."default",
    media_type text COLLATE pg_catalog."default",
    mime_type text COLLATE pg_catalog."default",
    width integer,
    height integer,
    duration_seconds integer,
    size_bytes bigint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT media_pkey PRIMARY KEY (media_id)
);

CREATE TABLE IF NOT EXISTS media.message_attachments
(
    message_id uuid NOT NULL,
    media_id uuid NOT NULL,
    CONSTRAINT message_attachments_pkey PRIMARY KEY (message_id, media_id)
);

CREATE TABLE IF NOT EXISTS media.post_media
(
    post_id uuid NOT NULL,
    media_id uuid NOT NULL,
    sort_order integer,
    CONSTRAINT post_media_pkey PRIMARY KEY (post_id, media_id)
);

CREATE TABLE IF NOT EXISTS media.user_media
(
    user_id uuid NOT NULL,
    media_id uuid NOT NULL,
    kind text COLLATE pg_catalog."default" NOT NULL,
    sort_order integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_media_pkey PRIMARY KEY (user_id, media_id, kind)
);

CREATE TABLE IF NOT EXISTS music.genres
(
    genre_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."default" NOT NULL,
    normalized_name text COLLATE pg_catalog."default",
    source text COLLATE pg_catalog."default",
    external_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT genres_pkey PRIMARY KEY (genre_id),
    CONSTRAINT uq_genres_normalized_name UNIQUE (normalized_name)
);

CREATE TABLE IF NOT EXISTS music.instrument
(
    instrument_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."default" NOT NULL,
    normalized_name text COLLATE pg_catalog."default",
    category text COLLATE pg_catalog."default",
    source text COLLATE pg_catalog."default",
    external_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT instrument_pkey PRIMARY KEY (instrument_id),
    CONSTRAINT uq_instrument_normalized_name UNIQUE (normalized_name)
);

CREATE TABLE IF NOT EXISTS music.musician_genre
(
    musician_genre_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    genre_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT musician_genre_pkey PRIMARY KEY (musician_genre_id),
    CONSTRAINT uq_musician_genre_user_id_genre_id UNIQUE (user_id, genre_id)
);

CREATE TABLE IF NOT EXISTS music.musician_instrument
(
    musician_instrument_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    instrument_id uuid NOT NULL,
    level text COLLATE pg_catalog."default",
    is_primary boolean DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT musician_instrument_pkey PRIMARY KEY (musician_instrument_id),
    CONSTRAINT uq_musician_instrument_user_id_instrument_id UNIQUE (user_id, instrument_id)
);

CREATE TABLE IF NOT EXISTS music.musician_profile
(
    musician_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    years_experience integer,
    skill_summary text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT musician_profile_pkey PRIMARY KEY (musician_id),
    CONSTRAINT uq_musician_profile_user_id UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS notifications.email_outbox
(
    email_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    to_email citext COLLATE pg_catalog."default",
    template text COLLATE pg_catalog."default",
    subject text COLLATE pg_catalog."default",
    payload jsonb,
    status text COLLATE pg_catalog."default",
    provider_message_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    sent_at timestamp with time zone,
    error text COLLATE pg_catalog."default",
    CONSTRAINT email_outbox_pkey PRIMARY KEY (email_id)
);

CREATE TABLE IF NOT EXISTS notifications.notifications
(
    notification_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    notification_type text COLLATE pg_catalog."default",
    payload jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    read_at timestamp with time zone,
    delivered_at timestamp with time zone,
    CONSTRAINT notifications_pkey PRIMARY KEY (notification_id)
);

CREATE TABLE IF NOT EXISTS notifications.push_subscriptions
(
    subscription_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    platform text COLLATE pg_catalog."default",
    token text COLLATE pg_catalog."default",
    device_id uuid NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    last_seen_at timestamp with time zone,
    CONSTRAINT push_subscriptions_pkey PRIMARY KEY (subscription_id),
    CONSTRAINT uq_push_subscriptions_platform_token UNIQUE (platform, token)
);

CREATE TABLE IF NOT EXISTS payments.payment_webhooks
(
    payment_webhook_id uuid NOT NULL DEFAULT gen_random_uuid(),
    webhook_id uuid NOT NULL,
    payment_id uuid NOT NULL,
    provider text COLLATE pg_catalog."default",
    event_type text COLLATE pg_catalog."default",
    payload jsonb,
    received_at timestamp with time zone,
    processed_at timestamp with time zone,
    processing_error text COLLATE pg_catalog."default",
    CONSTRAINT payment_webhooks_pkey PRIMARY KEY (payment_webhook_id)
);

CREATE TABLE IF NOT EXISTS payments.payments
(
    payment_id uuid NOT NULL DEFAULT gen_random_uuid(),
    booking_id uuid NOT NULL,
    provider text COLLATE pg_catalog."default",
    amount numeric(12, 2),
    currency character(3) COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    status_detail text COLLATE pg_catalog."default",
    mp_preference_id uuid NOT NULL,
    mp_payment_id uuid NOT NULL,
    mp_merchant_order_id uuid NOT NULL,
    external_reference text COLLATE pg_catalog."default",
    raw_last_response jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    approved_at timestamp with time zone,
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS payments.refunds
(
    refund_id uuid NOT NULL DEFAULT gen_random_uuid(),
    payment_id uuid NOT NULL,
    provider_refund_id uuid NOT NULL,
    amount numeric(12, 2),
    status text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT refunds_pkey PRIMARY KEY (refund_id)
);

CREATE TABLE IF NOT EXISTS reviews.reports
(
    report_id uuid NOT NULL DEFAULT gen_random_uuid(),
    reporter_user_id uuid NOT NULL,
    target_type text COLLATE pg_catalog."default",
    target_id uuid NOT NULL,
    reason text COLLATE pg_catalog."default",
    details text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    resolved_at timestamp with time zone,
    resolved_by uuid,
    CONSTRAINT reports_pkey PRIMARY KEY (report_id)
);

CREATE TABLE IF NOT EXISTS reviews.studio_reviews
(
    studio_review_id uuid NOT NULL DEFAULT gen_random_uuid(),
    studio_id uuid NOT NULL,
    user_id uuid NOT NULL,
    rating smallint,
    comment text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT studio_reviews_pkey PRIMARY KEY (studio_review_id),
    CONSTRAINT uq_studio_reviews_studio_id_user_id UNIQUE (studio_id, user_id)
);

CREATE TABLE IF NOT EXISTS reviews.user_reviews
(
    user_review_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_reviewed_id uuid NOT NULL,
    user_reviewer_id uuid NOT NULL,
    rating smallint,
    comment text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_reviews_pkey PRIMARY KEY (user_review_id),
    CONSTRAINT uq_user_reviews_user_reviewed_id_user_reviewer_id UNIQUE (user_reviewed_id, user_reviewer_id)
);

CREATE TABLE IF NOT EXISTS social.blocks
(
    block_id uuid NOT NULL DEFAULT gen_random_uuid(),
    blocker_user_id uuid NOT NULL,
    blocked_user_id uuid NOT NULL,
    reason text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT blocks_pkey PRIMARY KEY (block_id),
    CONSTRAINT uq_blocks_blocker_user_id_blocked_user_id UNIQUE (blocker_user_id, blocked_user_id)
);

CREATE TABLE IF NOT EXISTS social.follows
(
    follower_user_id uuid NOT NULL,
    target_type text COLLATE pg_catalog."default" NOT NULL,
    target_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT follows_pkey PRIMARY KEY (follower_user_id, target_type, target_id)
);

CREATE TABLE IF NOT EXISTS social.friend_requests
(
    request_id uuid NOT NULL DEFAULT gen_random_uuid(),
    from_user_id uuid NOT NULL,
    to_user_id uuid NOT NULL,
    message text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    responded_at timestamp with time zone,
    CONSTRAINT friend_requests_pkey PRIMARY KEY (request_id),
    CONSTRAINT uq_friend_requests_from_user_id_to_user_id UNIQUE (from_user_id, to_user_id)
);

CREATE TABLE IF NOT EXISTS social.friendships
(
    friendship_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id1 uuid NOT NULL,
    user_id2 uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT friendships_pkey PRIMARY KEY (friendship_id),
    CONSTRAINT uq_friendships_user_id1_user_id2 UNIQUE (user_id1, user_id2)
);

CREATE TABLE IF NOT EXISTS studios.equipment
(
    equipment_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."default" NOT NULL,
    category text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT equipment_pkey PRIMARY KEY (equipment_id)
);

CREATE TABLE IF NOT EXISTS studios.rehearsal_rooms
(
    room_id uuid NOT NULL DEFAULT gen_random_uuid(),
    studio_id uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    capacity integer,
    base_hourly_price numeric(12, 2),
    min_booking_minutes integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT rehearsal_rooms_pkey PRIMARY KEY (room_id)
);

CREATE TABLE IF NOT EXISTS studios.room_availability_rules
(
    rule_id uuid NOT NULL DEFAULT gen_random_uuid(),
    room_id uuid NOT NULL,
    day_of_week smallint,
    start_time time without time zone,
    end_time time without time zone,
    timezone text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT room_availability_rules_pkey PRIMARY KEY (rule_id)
);

CREATE TABLE IF NOT EXISTS studios.room_blocks
(
    block_id uuid NOT NULL DEFAULT gen_random_uuid(),
    room_id uuid NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    ends_at timestamp with time zone NOT NULL,
    reason text COLLATE pg_catalog."default",
    created_by uuid,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT room_blocks_pkey PRIMARY KEY (block_id)
);

CREATE TABLE IF NOT EXISTS studios.room_equipment
(
    room_equipment_id uuid NOT NULL DEFAULT gen_random_uuid(),
    room_id uuid NOT NULL,
    equipment_id uuid NOT NULL,
    quantity text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT room_equipment_pkey PRIMARY KEY (room_equipment_id),
    CONSTRAINT uq_room_equipment_room_id_equipment_id UNIQUE (room_id, equipment_id)
);

CREATE TABLE IF NOT EXISTS studios.studios
(
    studio_id uuid NOT NULL DEFAULT gen_random_uuid(),
    owner_user_id uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    place_id uuid,
    phone text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT studios_pkey PRIMARY KEY (studio_id)
);

ALTER TABLE IF EXISTS auth.email_verification_tokens
    ADD CONSTRAINT email_verification_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_email_verif_tokens_user_id
    ON auth.email_verification_tokens(user_id);


ALTER TABLE IF EXISTS auth.oauth_accounts
    ADD CONSTRAINT fk_oauth_accounts_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_oauth_accounts_user_id
    ON auth.oauth_accounts(user_id);


ALTER TABLE IF EXISTS auth.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_pwreset_tokens_user_id
    ON auth.password_reset_tokens(user_id);


ALTER TABLE IF EXISTS auth.sessions
    ADD CONSTRAINT fk_sessions_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_sessions_user_id
    ON auth.sessions(user_id);


ALTER TABLE IF EXISTS auth.user_roles
    ADD CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_user_roles_user_id
    ON auth.user_roles(user_id);


ALTER TABLE IF EXISTS auth.users
    ADD CONSTRAINT fk_users_place_id FOREIGN KEY (place_id)
    REFERENCES geo.places (place_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_users_place_id
    ON auth.users(place_id);


ALTER TABLE IF EXISTS bands.band_genres
    ADD CONSTRAINT fk_band_genres_band_id FOREIGN KEY (band_id)
    REFERENCES bands.bands (band_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS bands.band_genres
    ADD CONSTRAINT fk_band_genres_genre_id FOREIGN KEY (genre_id)
    REFERENCES music.genres (genre_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS bands.band_invite
    ADD CONSTRAINT fk_band_invite_band_id FOREIGN KEY (band_id)
    REFERENCES bands.bands (band_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_band_invite_band_id
    ON bands.band_invite(band_id);


ALTER TABLE IF EXISTS bands.band_invite
    ADD CONSTRAINT fk_band_invite_from_user_id FOREIGN KEY (from_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS bands.band_invite
    ADD CONSTRAINT fk_band_invite_to_user_id FOREIGN KEY (to_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_band_invite_to_user_id
    ON bands.band_invite(to_user_id);


ALTER TABLE IF EXISTS bands.band_members
    ADD CONSTRAINT fk_band_members_band_id FOREIGN KEY (band_id)
    REFERENCES bands.bands (band_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_band_members_band_id
    ON bands.band_members(band_id);


ALTER TABLE IF EXISTS bands.band_members
    ADD CONSTRAINT fk_band_members_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_band_members_user_id
    ON bands.band_members(user_id);


ALTER TABLE IF EXISTS bands.band_openings
    ADD CONSTRAINT fk_band_openings_band_id FOREIGN KEY (band_id)
    REFERENCES bands.bands (band_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_band_openings_band_id
    ON bands.band_openings(band_id);


ALTER TABLE IF EXISTS bands.band_openings
    ADD CONSTRAINT fk_band_openings_instrument_id FOREIGN KEY (instrument_id)
    REFERENCES music.instrument (instrument_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_band_openings_instrument_id
    ON bands.band_openings(instrument_id);


ALTER TABLE IF EXISTS bands.band_openings
    ADD CONSTRAINT fk_band_openings_place_id FOREIGN KEY (place_id)
    REFERENCES geo.places (place_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_band_openings_place_id
    ON bands.band_openings(place_id);


ALTER TABLE IF EXISTS bands.bands
    ADD CONSTRAINT fk_bands_owner_user_id FOREIGN KEY (owner_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS ix_bands_owner_user_id
    ON bands.bands(owner_user_id);


ALTER TABLE IF EXISTS bands.bands
    ADD CONSTRAINT fk_bands_place_id FOREIGN KEY (place_id)
    REFERENCES geo.places (place_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_bands_place_id
    ON bands.bands(place_id);


ALTER TABLE IF EXISTS bands.opening_applications
    ADD CONSTRAINT fk_opening_applications_opening_id FOREIGN KEY (opening_id)
    REFERENCES bands.band_openings (opening_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_opening_applications_opening_id
    ON bands.opening_applications(opening_id);


ALTER TABLE IF EXISTS bands.opening_applications
    ADD CONSTRAINT fk_opening_applications_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_opening_applications_user_id
    ON bands.opening_applications(user_id);


ALTER TABLE IF EXISTS bookings.booking_status_history
    ADD CONSTRAINT fk_booking_status_history_booking_id FOREIGN KEY (booking_id)
    REFERENCES bookings.bookings (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS bookings.booking_status_history
    ADD CONSTRAINT fk_booking_status_history_changed_by FOREIGN KEY (changed_by)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS bookings.bookings
    ADD CONSTRAINT fk_bookings_room_id FOREIGN KEY (room_id)
    REFERENCES studios.rehearsal_rooms (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS bookings.bookings
    ADD CONSTRAINT fk_bookings_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS bookings.receipts
    ADD CONSTRAINT fk_receipts_booking_id FOREIGN KEY (booking_id)
    REFERENCES bookings.bookings (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS uq_receipts_booking_id
    ON bookings.receipts(booking_id);


ALTER TABLE IF EXISTS chat.conversation_members
    ADD CONSTRAINT fk_conversation_members_conversation_id FOREIGN KEY (conversation_id)
    REFERENCES chat.conversations (conversation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS chat.conversation_members
    ADD CONSTRAINT fk_conversation_members_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_conversation_members_user_id
    ON chat.conversation_members(user_id);


ALTER TABLE IF EXISTS chat.message_reads
    ADD CONSTRAINT fk_message_reads_message_id FOREIGN KEY (message_id)
    REFERENCES chat.messages (message_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS chat.message_reads
    ADD CONSTRAINT fk_message_reads_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS chat.messages
    ADD CONSTRAINT fk_messages_conversation_id FOREIGN KEY (conversation_id)
    REFERENCES chat.conversations (conversation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS chat.messages
    ADD CONSTRAINT fk_messages_sender_user_id FOREIGN KEY (sender_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS events.event_attendees
    ADD CONSTRAINT fk_event_attendees_event_id FOREIGN KEY (event_id)
    REFERENCES events.events (event_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS events.event_attendees
    ADD CONSTRAINT fk_event_attendees_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_event_attendees_user_id
    ON events.event_attendees(user_id);


ALTER TABLE IF EXISTS events.event_band_attendance
    ADD CONSTRAINT fk_event_band_attendance_band_id FOREIGN KEY (band_id)
    REFERENCES bands.bands (band_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_event_band_attendance_band_id
    ON events.event_band_attendance(band_id);


ALTER TABLE IF EXISTS events.event_band_attendance
    ADD CONSTRAINT fk_event_band_attendance_event_id FOREIGN KEY (event_id)
    REFERENCES events.events (event_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS events.event_invites
    ADD CONSTRAINT fk_event_invites_event_id FOREIGN KEY (event_id)
    REFERENCES events.events (event_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS events.event_invites
    ADD CONSTRAINT fk_event_invites_from_user_id FOREIGN KEY (from_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS events.event_invites
    ADD CONSTRAINT fk_event_invites_to_user_id FOREIGN KEY (to_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_event_invites_to_user_id
    ON events.event_invites(to_user_id);


ALTER TABLE IF EXISTS events.events
    ADD CONSTRAINT fk_events_host_band_id FOREIGN KEY (host_band_id)
    REFERENCES bands.bands (band_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_events_host_band_id
    ON events.events(host_band_id);


ALTER TABLE IF EXISTS events.events
    ADD CONSTRAINT fk_events_host_user_id FOREIGN KEY (host_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS ix_events_host_user_id
    ON events.events(host_user_id);


ALTER TABLE IF EXISTS events.events
    ADD CONSTRAINT fk_events_place_id FOREIGN KEY (place_id)
    REFERENCES geo.places (place_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS media.message_attachments
    ADD CONSTRAINT fk_message_attachments_media_id FOREIGN KEY (media_id)
    REFERENCES media.media (media_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS media.message_attachments
    ADD CONSTRAINT fk_message_attachments_message_id FOREIGN KEY (message_id)
    REFERENCES chat.messages (message_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_message_attachments_message_id
    ON media.message_attachments(message_id);


ALTER TABLE IF EXISTS media.post_media
    ADD CONSTRAINT fk_post_media_media_id FOREIGN KEY (media_id)
    REFERENCES media.media (media_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS media.user_media
    ADD CONSTRAINT fk_user_media_media_id FOREIGN KEY (media_id)
    REFERENCES media.media (media_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_user_media_media_id
    ON media.user_media(media_id);


ALTER TABLE IF EXISTS media.user_media
    ADD CONSTRAINT fk_user_media_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_user_media_user_id
    ON media.user_media(user_id);


ALTER TABLE IF EXISTS music.musician_genre
    ADD CONSTRAINT fk_musician_genre_genre_id FOREIGN KEY (genre_id)
    REFERENCES music.genres (genre_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_musician_genre_genre_id
    ON music.musician_genre(genre_id);


ALTER TABLE IF EXISTS music.musician_genre
    ADD CONSTRAINT fk_musician_genre_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_musician_genre_user_id
    ON music.musician_genre(user_id);


ALTER TABLE IF EXISTS music.musician_instrument
    ADD CONSTRAINT fk_musician_instrument_instrument_id FOREIGN KEY (instrument_id)
    REFERENCES music.instrument (instrument_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_musician_instrument_instrument_id
    ON music.musician_instrument(instrument_id);


ALTER TABLE IF EXISTS music.musician_instrument
    ADD CONSTRAINT fk_musician_instrument_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_musician_instrument_user_id
    ON music.musician_instrument(user_id);


ALTER TABLE IF EXISTS music.musician_profile
    ADD CONSTRAINT fk_musician_profile_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS uq_musician_profile_user_id
    ON music.musician_profile(user_id);


ALTER TABLE IF EXISTS notifications.email_outbox
    ADD CONSTRAINT fk_email_outbox_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS notifications.notifications
    ADD CONSTRAINT fk_notifications_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_notifications_user_id
    ON notifications.notifications(user_id);


ALTER TABLE IF EXISTS notifications.push_subscriptions
    ADD CONSTRAINT fk_push_subscriptions_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_push_subscriptions_user_id
    ON notifications.push_subscriptions(user_id);


ALTER TABLE IF EXISTS payments.payment_webhooks
    ADD CONSTRAINT fk_payment_webhooks_payment_id FOREIGN KEY (payment_id)
    REFERENCES payments.payments (payment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS payments.payments
    ADD CONSTRAINT fk_payments_booking_id FOREIGN KEY (booking_id)
    REFERENCES bookings.bookings (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_payments_booking_id
    ON payments.payments(booking_id);


ALTER TABLE IF EXISTS payments.refunds
    ADD CONSTRAINT fk_refunds_payment_id FOREIGN KEY (payment_id)
    REFERENCES payments.payments (payment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_refunds_payment_id
    ON payments.refunds(payment_id);


ALTER TABLE IF EXISTS reviews.reports
    ADD CONSTRAINT fk_reports_reporter_user_id FOREIGN KEY (reporter_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS reviews.reports
    ADD CONSTRAINT fk_reports_resolved_by FOREIGN KEY (resolved_by)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS reviews.studio_reviews
    ADD CONSTRAINT fk_studio_reviews_studio_id FOREIGN KEY (studio_id)
    REFERENCES studios.studios (studio_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_studio_reviews_studio_id
    ON reviews.studio_reviews(studio_id);


ALTER TABLE IF EXISTS reviews.studio_reviews
    ADD CONSTRAINT fk_studio_reviews_user_id FOREIGN KEY (user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_studio_reviews_user_id
    ON reviews.studio_reviews(user_id);


ALTER TABLE IF EXISTS reviews.user_reviews
    ADD CONSTRAINT fk_user_reviews_user_reviewed_id FOREIGN KEY (user_reviewed_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_user_reviews_user_reviewed_id
    ON reviews.user_reviews(user_reviewed_id);


ALTER TABLE IF EXISTS reviews.user_reviews
    ADD CONSTRAINT fk_user_reviews_user_reviewer_id FOREIGN KEY (user_reviewer_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS social.blocks
    ADD CONSTRAINT fk_blocks_blocked_user_id FOREIGN KEY (blocked_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_blocks_blocked_user_id
    ON social.blocks(blocked_user_id);


ALTER TABLE IF EXISTS social.blocks
    ADD CONSTRAINT fk_blocks_blocker_user_id FOREIGN KEY (blocker_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS social.follows
    ADD CONSTRAINT fk_follows_follower_user_id FOREIGN KEY (follower_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS social.friend_requests
    ADD CONSTRAINT fk_friend_requests_from_user_id FOREIGN KEY (from_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_friend_requests_from_user_id
    ON social.friend_requests(from_user_id);


ALTER TABLE IF EXISTS social.friend_requests
    ADD CONSTRAINT fk_friend_requests_to_user_id FOREIGN KEY (to_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS social.friendships
    ADD CONSTRAINT fk_friendships_user_id1 FOREIGN KEY (user_id1)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_friendships_user_id1
    ON social.friendships(user_id1);


ALTER TABLE IF EXISTS social.friendships
    ADD CONSTRAINT fk_friendships_user_id2 FOREIGN KEY (user_id2)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_friendships_user_id2
    ON social.friendships(user_id2);


ALTER TABLE IF EXISTS studios.rehearsal_rooms
    ADD CONSTRAINT fk_rehearsal_rooms_studio_id FOREIGN KEY (studio_id)
    REFERENCES studios.studios (studio_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_rehearsal_rooms_studio_id
    ON studios.rehearsal_rooms(studio_id);


ALTER TABLE IF EXISTS studios.room_availability_rules
    ADD CONSTRAINT fk_room_availability_rules_room_id FOREIGN KEY (room_id)
    REFERENCES studios.rehearsal_rooms (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS studios.room_blocks
    ADD CONSTRAINT fk_room_blocks_created_by FOREIGN KEY (created_by)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS studios.room_blocks
    ADD CONSTRAINT fk_room_blocks_room_id FOREIGN KEY (room_id)
    REFERENCES studios.rehearsal_rooms (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS studios.room_equipment
    ADD CONSTRAINT fk_room_equipment_equipment_id FOREIGN KEY (equipment_id)
    REFERENCES studios.equipment (equipment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS studios.room_equipment
    ADD CONSTRAINT fk_room_equipment_room_id FOREIGN KEY (room_id)
    REFERENCES studios.rehearsal_rooms (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_room_equipment_room_id
    ON studios.room_equipment(room_id);


ALTER TABLE IF EXISTS studios.studios
    ADD CONSTRAINT fk_studios_owner_user_id FOREIGN KEY (owner_user_id)
    REFERENCES auth.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS ix_studios_owner_user_id
    ON studios.studios(owner_user_id);


ALTER TABLE IF EXISTS studios.studios
    ADD CONSTRAINT fk_studios_place_id FOREIGN KEY (place_id)
    REFERENCES geo.places (place_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_studios_place_id
    ON studios.studios(place_id);

END;